#!/bin/bash
# $Id: ci,v 1.2 2007/01/25 12:23:22 jettero Exp $
# vi:syntax=gentoo-init-d:

source /sbin/functions.sh
set -e; trap "eend 997" ERR

figlet 'Checking IN'

ebegin "pulling/merging updates"
cg update
eend $?

ebegin "rcskeywords -m"
rcskeywords -m
eend $?

ebegin "updating update index (cache)"
(git-update-index --refresh >/dev/null)
einfo "(updated)";
eend $?

ebegin "committing changes"
if [ -z "$*" ]; then
    cg commit

else 
    cg commit -m "$*"
fi
eend $?

ebegin "pushing commit to repo"
cg push
eend $?

